services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./html:/var/www
        depends_on:
            - redis
            - db
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./html:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - db
        networks:
            - laravel

    # db mysql
    db:
        image: mysql:latest
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-intranet}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-12346}
            MYSQL_PASSWORD: ${DB_PASSWORD:-123456}
            MYSQL_USER: ${DB_USERNAME:-dbuser}
        volumes:
            - ./db_data:/var/lib/mysql
        ports:
            - "3300:3306"
        networks:
            - laravel

    # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/x86_64
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-123456}
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
